### ISSUE TITLE
Erste Tabelle Migration schlägt fehl idp_db.craue_form_flow_storage

### ISSUE THREAD

**Issue by LoPablo** [SchulIT/idp#86]
Hi, ich hab heute nochmal ein Testsystem aufgesetzt bin jedoch relativ lange beim Ausführen der Tabell-Migrationen hängen geblieben. Hier wirft mir Doctrine immer den Fehler, dass die Tabelle `idp_db.craue_form_flow_storage` nicht existiert.

![Bildschirmfoto 2023-11-27 um 22 03 52](https://github.com/SchulIT/idp/assets/28061988/06ffb108-c70b-4790-a821-34031fe167e1)

Die Tabelle einfach per Hand nur mit einem Id-Feld in MySql direkt zu erstellen, ermöglicht das fertig ausführen der Migration.

**Comment by frostieDE** [comment]
Hoppla, die Migration ist tatsächlich einfach überflüssig. Ich habe sie in 754a1be gelöscht :)
